import './globals.css'
import type { Metadata } from 'next'
import { Inter ,Saira_Stencil_One ,Hammersmith_One  ,Rajdhani ,Righteous} from 'next/font/google'
// import { Font } from '@fontsource/saira-stencil-one'
import BgContianerClr from './components/BgContianerClr'
import Nav from './components/Nav'
import Footer from './components/Footer'
// ("latin" | "latin-ext" | "vietnamese")[]; 
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'h-Quiz',
  description: 'Generated by create next app',
}

//write the code for use Saira_Stencil_One  font
export const headingFont = Saira_Stencil_One({ subsets: ['latin', 'latin-ext', 'vietnamese']  , weight:"400",
variable:  '--font-harish',

})
export const desscriptFont = Hammersmith_One({ subsets: ['latin', 'latin-ext'] , weight:"400"} )
export const commanFont = Rajdhani({ subsets: [ "latin" ,"latin-ext"] ,weight:"400" } )
export const subHeadingFont = Righteous({ subsets: [ "latin" ,"latin-ext"] ,weight:"400" } )






export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className }>

      <BgContianerClr >
    
      <main className='m-[8px] sm:m-[16px] md:m-[32px] lg:[64px]'>
<Nav  />
      {children}
  
      <Footer />

      </main>
      </BgContianerClr>
       </body>
    </html>
  )
}
